spring.application.name=msvc-uploadfile
server.port=8002

#DOCUMENT Api Rest con Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/doc/api-docs

#CONFIG STORAGE AZURE
config.azure.storage-url=https://uploadsphotos.blob.core.windows.net/images-vehicles/
config.azure.storage-connection=DefaultEndpointsProtocol=https;AccountName=resourcesfile;AccountKey=rAwPa9TcnT2jqBUY0I8PgTPHYFA4Q9ZdjzQBA6aL02zm7BrA2Qxc6W8zoqRPy+Hx1uPuS6yXkbYQ+AStWBul1g==;EndpointSuffix=core.windows.net
config.azure.storage-container=images-vehicles